version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password # The password for the root user
      MYSQL_DATABASE: your_database_name # The name of the database to create
      MYSQL_USER: your_database_user # A new user for your application
      MYSQL_PASSWORD: your_database_password # Password for the application user
    ports:
      - "3306:3306"  # Exposing MySQL port to the host machine
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data across container restarts

volumes:
  mysql-data:
